# Generated by Django 3.2.9 on 2022-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='text',
            name='photo2',
            field=models.ImageField(default='default photo', upload_to='img'),
            preserve_default=False,
        ),
    ]
